"""Text harness — the brain's test bench. No voice, no room, no keys.

    python scripts/harness.py "what's blocking the auth migration?" [persona_id]

Pipes a question through retrieve() and prints the retrieved chunks (the 🔎 trace).
Use it to: (Nuha) check retrieval quality, (Melody) check her corpus surfaces the
right chunk for the demo question, (Tony) sanity-check the contract.
"""
import asyncio
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), os.pardir))

from brain.retrieval import retrieve  # noqa: E402
from personas import get_persona      # noqa: E402


async def main() -> None:
    query = sys.argv[1] if len(sys.argv) > 1 else "what's blocking the auth migration?"
    persona_id = sys.argv[2] if len(sys.argv) > 2 else "person_a"
    persona = get_persona(persona_id)

    chunks = await retrieve(query, persona_id)

    print(f"\nQ -> {persona.name}: {query}\n")
    print("🔎 Moss -> retrieved:")
    if not chunks:
        print("  (nothing found)")
    for c in chunks:
        print(f"  [{c.score}] {c.ref} ({c.source}): {c.text}")

    print("\nGrounded answer would be generated by the LLM with the top chunk(s) as context.")
    if chunks:
        print(f"  -> grounds on: {chunks[0].ref}")


if __name__ == "__main__":
    asyncio.run(main())
